npm/npm-registry-fetch

- errors.js
- test/errors.js
If we can't identify the auth problem we should pass it through with default settings. (This was an error in the npm-profile implementation.)
> fix(errors): Unknown auth errors use default code

- package-lock.json
- package.json
This removes an implicit transitive dependency that itself relies on node_modules being flattened by package managers.
Without this explicit dependency, stricter package managers like pnpm fail to install a usable copy of this library.
Refs npm/libnpmaccess#2
Fixes #3
For example:
```sh
npm -g i pnpm
mkdir -p /tmp/pnpm-npm-registry-fetch
cd /tmp/pnpm-npm-registry-fetch
npm init -y
pnpm i npm-registry-fetch
node -p 'require("npm-registry-fetch")'
```
The last line dumps this error to the console:
```txt
internal/modules/cjs/loader.js:584
throw err;
^
Error: Cannot find module 'safe-buffer'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
at Function.Module._load (internal/modules/cjs/loader.js:508:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at …
```
> fix(deps): Add explicit dependency on safe-buffer

- test/check-response.js
- test/index.js
Added missing tests for `check-response.js` module in order to bump coverage.
- Added test coverage for warning header usage cases
- Added missing check for silenced errors when reading Responses
- Added check for correctly logging x-fetch-attempts header value
> test(check-response): Added missing tests

- check-response.js
Prevents `npm-registry-fetch` from leaking passwords on logs.
> chore: hide sensitive data from logs

- auth.js
- check-response.js
- errors.js
- index.js
- test/auth.js
- test/cache.js
- test/check-response.js
- test/errors.js
- test/index.js
This refactors the handling of auth in the new context where npm/cli
will _only_ ever send authorization in such a way that any
authorization-related options are scoped to a given sanitized registry
host and path.
This fixes a troubling situation where a user has intentionally logged
into two separate registries, one which serves package distribution
tarballs, and the other which has packuments pointing to it.
For example, a request to `https://registry.internal/private-thing`
might return this packument:
```json
{
"name": "private-thing",
"dist-tags": {
"latest": "1.0.0"
},
"versions": {
"1.0.0": {
"name": "private-thing",
"version": "1.0.0",
"dist": {
"tarball": "https://tarballs.internal/private-thing-1.0.0.tgz"
}
}
}
}
```
If the user has properly logged into both …
> Load and send auth based on URI, not registry

- README.md
- index.js
- test/errors.js
Based on #41, land that first.
This adds support for an opts.otpPrompt function which will be called
whenever an OTP is needed.  The request will then be retried with the
OTP provided.  If the method throws or fails to provide an OTP value,
then the 401 error is raised.
> Adds opts.otpPrompt to provide an OTP on demand

- auth.js
- test/auth.js
If the auth object was created from a username and a password, we need
to know about it.  This adds a flag for us to use to know this info
> feat(auth): set isBasicAuth

- README.md
`registry` no longer affects auth across domains
> fix(docs): update registry param

- README.md
Fix minor typo of 'yeader' within description of opts.npmCommand
> docs: fix header typo for npm-command

- check-response.js
- package-lock.json
- package.json
- test/check-response.js
- test/index.js
The `Warning` header has been deprecated, so let's not deal with it any more.
This will be necessary when we update make-fetch-happen after npm/make-fetch-happen#49 lands
Related to npm/make-fetch-happen#49
> BREAKING CHANGE: remove handling of deprecated warning headers

- README.md
- lib/index.js
- test/index.js
BREAKING CHANGE: this changes the name of an opts attribute from
`projectScope` to `scope`
> feat(opts): use scope instead of projectScope

- lib/index.js
`cacheManager` is deprecated in favor of `cachePath`. `cacheManager` is not documented so I was confused how npm-fetch-registry was caching without setting `cachePath`.
Searching for `cacheManager` in make-fetch-happen explains it:
https://github.com/npm/make-fetch-happen/blob/4d7b9c7e9f243258bff8329eba0beae448304af8/lib/options.js#L36-L42
This update should be safe because m-f-h is already copying the option to cachePath.
> chore: change deprecated cacheManager to cachePath

- lib/auth.js
Even though the engines field limits the range of node versions to those
that have a global URL, all but one of the files still used
require('url').URL.  This fixes the one remaining file to also use that.
While older versions of node are still not supported, and not
recommended, this will allow this module to potentially still work there
for the time being.
> fix: consistent use of url.URL

- README.md
- lib/check-response.js
- lib/default-opts.js
- package.json
- test/auth.js
- test/cache.js
- test/check-response.js
- test/errors.js
- test/index.js
BREAKING CHANGE: this drops support for passing in a `log` property. All
logs are now emitted on the process object via `proc-log`
> feat: use proc-log and drop npmlog support

- lib/errors.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> fix: replace deprecated String.prototype.substr()

- lib/index.js
- test/index.js
Set the `npm-auth-type` header to the value of the `--auth-type` command line parameter.
Allows the registry to know if the `npm` client is capable of handling new web based flows for commands that require extra verification steps.
- Closes https://github.com/github/npm/issues/5465
- https://github.com/github/npm/issues/5361
- https://github.com/github/npm/issues/5218
> feat: set 'npm-auth-type' header depending on config option

- README.md
- lib/default-opts.js
> docs: update API documentation of noProxy option

- lib/clean-url.js
I was asked to open a PR here because it doesn't seem to have that significant risk to npm, but it's best practice to fix this issue, So I just took a copy of the report reported to GitHub Security Team at [HackerOne](https://hackerone.com/) with ID `1917565`, that's the full details for the issue including the fix for this issue
An invalid replacement has been discovered on npm-cli function `replaceInfo` that's responsible for removing passwords from URLs getting passed to npm, to disallow it from being stored and saved on the logs exposing users passwords since there's many custom private registries at the time that big companies uses
Normally the format of HTTP basic authentication credentials is `http://username:password@hostname/path`, the `replaceInfo` function is just replacing the …
> fix: clean password by using url object itself

- package.json
- test/check-response.js
- test/errors.js
Breaking change was in `exports` which does not affect how this package uses it.
> deps: @npmcli/redact@2.0.0

- lib/errors.js
- test/errors.js
fix: allow HttpErrorBase to take headers object
> fix: make ErrorBase always capture stack trace

- .github/workflows/audit.yml
- .github/workflows/ci-release.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/post-dependabot.yml
- .github/workflows/pull-request.yml
- .github/workflows/release-integration.yml
- .github/workflows/release.yml
- .gitignore
- package.json
- release-please-config.json
- **deps: @npmcli/template-oss@4.25.0**
- **fix!: align to npm 11 node engine range**
- **chore: template-oss apply fix**
> deps & engine update
